// Generated by daily_content_manager.py on 2025-12-18 12:54:48
const drawingsConfig = [
    {
        "id": 1,
        "title": "Robot Space",
        "img": "assets/images/coloring_robot_space.png",
        "premium": false,
        "age": "6-9"
    },
    {
        "id": 2,
        "title": "Cute Cat",
        "img": "assets/images/coloring_cute_cat.png",
        "premium": false,
        "age": "3-5"
    },
    {
        "id": 3,
        "title": "Dino",
        "img": "assets/images/coloring_dino.png",
        "premium": false,
        "age": "6-9"
    },
    {
        "id": 4,
        "title": "Mandala Complex",
        "img": "assets/images/coloring_mandala_complex.png",
        "premium": false,
        "age": "10+"
    }
];