// Generated by daily_content_manager.py on 2025-12-18 12:54:48
const gamesConfig = [
    {
        "id": 1,
        "title": "Space Maze",
        "img": "assets/images/game_maze_rocket.png",
        "type": "Puzzle",
        "premium": false,
        "url": "games/maze.html",
        "age": "6-9"
    },
    {
        "id": 2,
        "title": "Memory Match",
        "img": "assets/images/coloring_cute_cat.png",
        "type": "Memory",
        "premium": false,
        "url": "games/memory.html",
        "age": "3-5"
    },
    {
        "id": 3,
        "title": "Math Blaster",
        "img": "assets/images/coloring_robot_space.png",
        "type": "Educational",
        "premium": true,
        "url": "games/math.html",
        "age": "6-9"
    }
];