// --- DYNAMIC CONTENT CONFIGURATION ---
// Generated by daily_content_manager.py on 2025-12-18 07:09:14.601453
// DO NOT EDIT MANUALLY.

const storiesConfig = [
    {
        "id": 1,
        "img": "assets/images/coloring_robot_space.png",
        "age": "3-5",
        "premium": false,
        "content": {
            "en": {
                "title": "Sparky the Robot",
                "text": "Once upon a time, there was a little robot named Sparky. He loved to fly among the stars. One day, he landed on a purple planet where the rocks sang happy songs!"
            },
            "ro": {
                "title": "Robotul Sparky",
                "text": "A fost odat\u0103 un robot mic pe nume Sparky. Lui \u00eei pl\u0103cea s\u0103 zboare printre stele. \u00centr-o zi, a ajuns pe o planet\u0103 mov unde pietrele c\u00e2ntau c\u00e2ntece vesele!"
            }
        }
    },
    {
        "id": 2,
        "img": "assets/images/coloring_dino.png",
        "age": "3-5",
        "premium": false,
        "content": {
            "en": {
                "title": "The Shy Dino",
                "text": "Dino was a big dinosaur with a very small voice. 'Squeak!' he said. His friends laughed, but Dino didn't mind. He talked to the butterflies and ants."
            },
            "ro": {
                "title": "Dino cel Timid",
                "text": "Dino era un dinozaur mare, dar cu o voce mic\u0103. 'Chi\u021b-chi\u021b!' f\u0103cea el. Prietenii lui r\u00e2deau, dar Dino nu se sup\u0103ra. El vorbea cu fluturii \u0219i furnicile."
            }
        }
    },
    {
        "id": 3,
        "img": "assets/images/coloring_submarine.png",
        "age": "6-9",
        "premium": false,
        "content": {
            "en": {
                "title": "Submarine Adventure",
                "text": "Captain Nemo and the yellow submarine dove deep into the ocean. They saw glowing fish and colorful corals. Suddenly, a friendly octopus waved at them!"
            },
            "ro": {
                "title": "Aventura Submarinului",
                "text": "C\u0103pitanul Nemo \u0219i submarinul galben s-au scufundat ad\u00e2nc \u00een ocean. Au v\u0103zut pe\u0219ti lumino\u0219i \u0219i corali colora\u021bi. Deodat\u0103, o caracati\u021b\u0103 prietenoas\u0103 le-a f\u0103cut cu m\u00e2na!' "
            }
        }
    },
    {
        "id": 4,
        "img": "assets/images/coloring_mandala_complex.png",
        "age": "10+",
        "premium": true,
        "content": {
            "en": {
                "title": "Mandala Mystery",
                "text": "Premium Content. Subscription required."
            },
            "ro": {
                "title": "Misterul Mandalei",
                "text": "Con\u021binut Premium. Necesit\u0103 abonament."
            }
        }
    }
];
