// --- DYNAMIC CONTENT CONFIGURATION ---
// Generated by daily_content_manager.py on 2025-12-18 12:39:47.582980
// DO NOT EDIT MANUALLY.

const storiesConfig = [
    {
        "id": 1,
        "img": "assets/images/coloring_robot_space.png",
        "age": "3-5",
        "premium": false,
        "content": {
            "en": {
                "title": "Sparky the Robot",
                "text": "Once upon a time, there was a little robot named Sparky. He loved to fly among the stars. One day, he landed on a purple planet where the rocks sang happy songs!"
            }
        }
    },
    {
        "id": 2,
        "img": "assets/images/coloring_dino.png",
        "age": "3-5",
        "premium": false,
        "content": {
            "en": {
                "title": "The Shy Dino",
                "text": "Dino was a big dinosaur with a very small voice. 'Squeak!' he said. His friends laughed, but Dino didn't mind. He talked to the butterflies and ants."
            }
        }
    },
    {
        "id": 3,
        "img": "assets/images/coloring_submarine.png",
        "age": "6-9",
        "premium": false,
        "content": {
            "en": {
                "title": "Submarine Adventure",
                "text": "Captain Nemo and the yellow submarine dove deep into the ocean. They saw glowing fish and colorful corals. Suddenly, a friendly octopus waved at them!"
            }
        }
    },
    {
        "id": 4,
        "img": "assets/images/coloring_mandala_complex.png",
        "age": "10+",
        "premium": true,
        "content": {
            "en": {
                "title": "Mandala Mystery",
                "text": "English Content. Subscription required."
            }
        }
    }
];
