[build]
  publish = "."
  functions = "netlify/functions"

# Fortam redirectarea de la radacina catre nexus.html
[[redirects]]
  from = "/"
  to = "/nexus.html"
  status = 200

[[redirects]]
  from = "/index.html"
  to = "/nexus.html"
  status = 301
