// Generated by daily_content_manager.py on 2025-12-18 12:54:48
const storiesConfig = [
    {
        "id": 1,
        "img": "assets/images/coloring_robot_space.png",
        "age": "3-5",
        "premium": false,
        "content": {
            "en": {
                "title": "Sparky the Robot",
                "text": "Once upon a time, there was a little robot named Sparky. He loved to fly among the stars. One day, he landed on a purple planet where the rocks sang happy songs!"
            }
        }
    },
    {
        "id": 2,
        "img": "assets/images/coloring_dino.png",
        "age": "3-5",
        "premium": false,
        "content": {
            "en": {
                "title": "The Shy Dino",
                "text": "Dino was a big dinosaur with a very small voice. 'Squeak!' he said. His friends laughed, but Dino didn't mind. He talked to the butterflies and ants."
            }
        }
    },
    {
        "id": 775,
        "img": "assets/images/logo_ae.png",
        "age": "3-5",
        "premium": false,
        "content": {
            "en": {
                "title": "The Robot Adventure",
                "text": "Once upon a time, there was a magical robot. It lived in a land of wonder!"
            }
        }
    },
    {
        "id": 790,
        "img": "assets/images/logo_ae.png",
        "age": "3-5",
        "premium": false,
        "content": {
            "en": {
                "title": "The Cat Adventure",
                "text": "Once upon a time, there was a magical cat. It lived in a land of wonder!"
            }
        }
    }
];